### ISSUE TITLE
[CannedAnalytics] Metabase setup status not shown correctly

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#854]
### Issue:
org: shelter, env: staging

- Currently even if creation of reports fails, on refresh of page when it is loading, it shows as 'Setup done'

<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/4394bb98-0991-41e3-9c73-314beeb46656" />

#### Tech detail:
- It is because in organisation_config table we are keeping track a variable called, ```metabaseSetupEnabled``` whose set value seems to be in contradiction with the success status of Metabase Canned Reports setup which is still under progress.
- Also we are setting the metabase via foreground thread and refresh of the page will not complete the setup, say in case metabase during refresh is only in its second step and collection creation which is 4th step may not get completed.
ie., /setup-toggle endpoint implementation needs to be made more robust so the status conveyed and shown in the UI is consistent. 

### AC:
- Status should not show as Done, when it is not Done.
- Refresh of the page or moving to a different page as well should show the status of Metabase setup correctly(ie., either loading or Done or the UI for not triggered)
- Should work in a consistent manner for orgs with large data as well.

### Code changes in repos (Release : 12.1)
- Avni-server
- Avni-webapp
- Avni-etl

**Comment by himeshr** [comment]
Moved back as other Metabase cards are in progress and we want to serialize the code changes to avoid conflicts

**Comment by petmongrels** [comment]
Technical AC: refactor the SelfServiceReports component code of managing state. It is too verbose at the moment.

**Comment by himeshr** [comment]
As part of this card, have only worked on handling Setup Status based on Avni and Metabase API responses.

For big organisations, Metabase Setup, though we see that SYNC is shown as completed, internally, the sync process might have failed in Metabase, due to column limit restrictions or other issues. Due to which, Avni would fail to automatically create Metabase Questions. Not sure how we could handle all issues arising there, and ensure all questions are always created.

**Comment by petmongrels** [comment]
change collection access to read only for the org user group

**Comment by petmongrels** [comment]
### QA notes
- also do sanity for subject migration batch job

**Comment by AchalaBelokar** [comment]
- [ ] In the prerelease report setup is not visible and on metabase it is showing the prerelease
-

**Comment by AchalaBelokar** [comment]
- [ ] Not to setup the metabase on staging and prerelease

**Comment by himeshr** [comment]
I deployed 12.1 webapp and server to staging, its working now

<img width="1840" alt="Image" src="https://github.com/user-attachments/assets/c9343579-4f20-47bb-aa04-6f2d96d0e53b" />

**Comment by AchalaBelokar** [comment]
- [ ] I deleted the reports after that it is showing me this error..
java.lang.RuntimeException: Table with name subject_view not found.
	at org.avni.server.dao.metabase.DatabaseRepository.lambda$findTableDetailsByName$3(DatabaseRepository.java:104)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.DatabaseRepository.findTableDetailsByName(DatabaseRepository.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.DatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionForTable(DatabaseService.java:111)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForViews(DatabaseService.java:200)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:282)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:60)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.

**Comment by himeshr** [comment]
Hi Achala, this card requires ETL to also be deployed and run successfully for the org.
Please deploy 12.1 etl to staging.

**Comment by AchalaBelokar** [comment]
- [ ] Tried with new deployments 12.1.0 on staging still facing the same problem

<img width="1418" alt="Image" src="https://github.com/user-attachments/assets/0cbdf86d-ece5-4220-8dc7-8db2f63adf79" />

**Comment by petmongrels** [comment]
I saw the error happen once. But I am not able to reproduce it again after that.
Lets test more.

**Comment by petmongrels** [comment]
@AchalaBelokar I have made some db change, so pls deploy server before testing again.

**Comment by AchalaBelokar** [comment]
- [ ] I tried with yenopya org on staging it is giving me this error. and setup is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://reporting-green.avniproject.org/api/dataset": Read timed out
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:895)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:507)
	at org.avni.server.dao.metabase.MetabaseConnector.postForObject(MetabaseConnector.java:67)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.getDataset(MetabaseDatabaseRepository.java:120)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findAll(MetabaseDatabaseRepository.java:130)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findAll(<generated>)
	at org.avni.server.service.metabase.DatabaseService.getTableMetadataRows(DatabaseService.java:160)
	at org.avni.server.service.metabase.DatabaseService.getProgramAndEncounterNames(DatabaseService.java:139)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForProgramsAndEncounters(DatabaseService.java:183)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:266)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.j

**Comment by AchalaBelokar** [comment]
- [ ] and I tried with 2nd time with same org it is giving java.lang.RuntimeException: Table with name subject_view not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$3(MetabaseDatabaseRepository.java:104)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionForTable(DatabaseService.java:114)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForViews(DatabaseService.java:203)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:270)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:65)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:78)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.a

**Comment by himeshr** [comment]
## TODO
- We'll replace calls to fetch table details call with a QueryMetadata call.
- We'll replace calls to fetch field details call with a QueryMetadata call. 
- Modify getSubjectTypeNames call to make use of TableMetadata on db rather than invoke call on Metabase.

[sampleQueryMetadataRequestCurl.txt](https://github.com/user-attachments/files/19317659/sampleQueryMetadataRequestCurl.txt)
[sampleQueryMetadata.json](https://github.com/user-attachments/files/19317658/sampleQueryMetadata.json)

**Comment by 1t5j0y** [comment]
commit - https://github.com/avniproject/avni-server/commit/d66194372c67af6e03d251c10eb78aafb8e77309

**Comment by 1t5j0y** [comment]
https://github.com/avniproject/avni-server/commit/d66194372c67af6e03d251c10eb78aafb8e77309#r154271978

**Comment by AchalaBelokar** [comment]
- [ ] 
- [ ] Login with acha@yenepoya and try to set the metabase report it is showing me this error
- [ ] org.springframework.web.client.HttpServerErrorException$BadGateway: 502 Bad Gateway: "<html><EOL><EOL><head><title>502 Bad Gateway</title></head><EOL><EOL><body><EOL><EOL><center><h1>502 Bad Gateway</h1></center><EOL><EOL></body><EOL><EOL></html><EOL><EOL>"
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:108)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
	at org.avni.server.dao.metabase.MetabaseConnector.getForObject(MetabaseConnector.java:77)
	at org.avni.server.dao.metabase.MetabaseGroupRepository.getAllGroups(MetabaseGroupRepository.java:50)
	at org.avni.server.dao.metabase.MetabaseGroupRepository.findGroup(MetabaseGroupRepository.java:34)
	at org.avni.server.dao.metabase.MetabaseGroupRepository.findGroup(MetabaseGroupRepository.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabas

**Comment by AchalaBelokar** [comment]
- [ ] This is happen with almost all organisation

**Comment by AchalaBelokar** [comment]
- [ ] I tried with maha@akrsp on staging it is giving me the error
java.lang.RuntimeException: Table with name control_group not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$3(MetabaseDatabaseRepository.java:112)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:112)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:121)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:130)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:223)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:66)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:79)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.sprin

**Comment by AchalaBelokar** [comment]
- [ ] Tried with maha@iphscd

java.lang.RuntimeException: Table with name control_group not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$3(MetabaseDatabaseRepository.java:112)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:112)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:121)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:130)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:223)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:66)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:79)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.sprin###

**Comment by mahalakshme** [comment]
@petmongrels Moved this card to 12.2.0

**Comment by himeshr** [comment]
Marking this as Tech-QA, as Achala is not able to determine error scenarios across organisations in one shot and there is lot of back and forth on the card.

As part of Tech-qa, we'll have more visibility of issues encountered across set of organisations, which can be tabulated and returned as a single fix requirement.

Important Note: After Tech QA is successful, we'll have a simple normal QA before closing the card

**Comment by mahalakshme** [comment]
@himeshr Just clarifying, after TechQA, Achala will need to test different scenarios across organisations as well.

**Comment by AchalaBelokar** [comment]
- [ ] tested on acha@yenpoya org it is giving me the error
 java.lang.RuntimeException: Table with name subject_view not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:112)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:112)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionForTable(DatabaseService.java:111)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForViews(DatabaseService.java:154)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:229)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:69)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:82)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.a

**Comment by mahalakshme** [comment]
- Metabase busy: check job time, archiving/unarchive, increasing specs.

**Comment by mahalakshme** [comment]
@AchalaBelokar moving to QA failed, but continue testing this.

**Comment by vedfordev** [comment]
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/c3a91b59-9d7d-453a-82d7-474c40209c7b" />

Getting error for due_visits_view and [Avni/etl](https://github.com/avniproject/avni-server/issues/843) is in review. 


I checked in log it is not showing view name
```
2025-04-04 08:49:10,184 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,647 INFO  Avni ETL_Worker-1 [etl.service.EtlService] New organisation after migration, schema summary IndividualEncounterCancellation-3;Person-1;HouseholdToMember-1;Household-1;SyncTelemetry-1;Media-1;ProgramEncounterCancellation-6;ProgramExit-5;User-1;Address-1;Encounter-3;ProgramEnrolment-5;MediaAnalysis-1;ProgramEncounter-7
2025-04-04 08:49:21,667 INFO  Avni ETL_Worker-1 [etl.repository.ReportingViewRepository] subject_view view created
2025-04-04 08:49:21,673 INFO  Avni ETL_Worker-1 [etl.repository.ReportingViewRepository] enrolment_view view created
2025-04-04 08:49:21,675 INFO  Avni ETL_Worker-1 [etl.service.SyncService] Migrating table yenepoya.individual of type Person
2025-04-04 08:49:21,684 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,739 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,742 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,745 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,746 INFO  Avni ETL_Worker-1 [etl.service.SyncService] Migrating table yenepoya.household of type Household
2025-04-04 08:49:21,756 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
2025-04-04 08:49:21,946 DEBUG Avni ETL_Worker-1 [etl.repository.JdbcContextWrapper] [yenepoya] Executing with dbUser: yenepoya
```

**Comment by ombhardwajj** [comment]
To fix `due_visits_view` not found error:

1. Deployed staging with [this commit](https://github.com/avniproject/avni-etl/commit/99ad7065cd188665591b80a70924a75255ea7ca0)
2. Removed the org DB and collection (tried to trigger resync and rescan values in Metabase but it didn't work - the buttons appear to work but nothing actually updates)

Tested with:
- Yenepoya - works fine
- AKRSP - works fine
- IPHSCD - strangely has `rwbniti` and other stuff in view (to be investigated further tomorrow)
- will test with some other orgs as well tomorrow

Noticed that `Error creating bean with name 'scopedTarget.cannedAnalyticsSetupTasklet'` error pops up in the 
**first attempt** whenever we try to **SETUP REPORTS** or **DELETE** them .

**Comment by ombhardwajj** [comment]
Seems to be working fine now . 
TechQA complete. 🚀 
Ready for normal QA

**Comment by AchalaBelokar** [comment]
- [x] Tested with yenopoya it is working fine but serach filter not contain dropdown list like when I am searching for village it is not showing the village list.
- [x] Tested with rwbniti reports are working fine
- [ ] Tested with maha2@jnpct-test and try to see on metabase but it is giving me error java.lang.RuntimeException: Table with name address not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:123)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:115)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:128)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:272)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:72)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframe


- [ ] Tested with goonj but there is working fine

**Comment by AchalaBelokar** [comment]
- [ ] Login with maha@rahi and try to setup it metabase report I got this report

**Comment by AchalaBelokar** [comment]
- [ ] Login with acha@jsscp on prerelease and then click on setup report it is giving me error.
tried with 2,3 times 
java.lang.RuntimeException: Table with name monthly_monitoring and schema: jsscp not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:120)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:111)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:120)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:264)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:78)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.

**Comment by AchalaBelokar** [comment]
- [ ] Login with dinesh@shelter on prerelease and delete option is not visible and then I  check etl status on readme then I click on setup report and then I get this error
java.lang.RuntimeException: Table with name address and schema: shelter not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:120)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:107)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:120)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:264)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:78)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)

- [ ] Login with mah@ashwini it is working fine but filter is not working as expected
- [ ] Login with maha@singrauli it is not working java.lang.RuntimeException: Table with name due_visits_view and schema: singrauli not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:120)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionForTable(DatabaseService.java:100)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForViews(DatabaseService.java:144)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:270)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:78)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)

**Comment by AchalaBelokar** [comment]
- [ ] Login with maha@chashma and also check on etl status 

java.lang.RuntimeException: Table with name address and schema: chashma not found.
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:120)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName(<generated>)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForEntities(DatabaseService.java:107)
	at org.avni.server.service.metabase.DatabaseService.createQuestionsForSubjectTypes(DatabaseService.java:120)
	at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:264)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:78)
	at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)

- [ ]

**Comment by mahalakshme** [comment]
@petmongrels Found the below issues when I was trying to setup.


1. Completed visits are not showing though there are completed visits

<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/394d70b4-272d-46c7-835d-0fffaeba64c5" />

<img width="1402" alt="Image" src="https://github.com/user-attachments/assets/b91f094e-ff45-4b84-b0de-e7aa1e7a47b5" />

Tried to refresh to see if it will work - but faced the below issue:
<img width="707" alt="Image" src="https://github.com/user-attachments/assets/a3fe7fbc-41f1-4ac5-8967-1205d3542553" />


2. Data is very less, so not sure why it is taking so much time to render the view.

**Comment by AchalaBelokar** [comment]
- [ ] Login with maha@rwbnitiuat and set up a metabase report it is successful but canned report is not showing.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/4a64a7bb-2932-4186-9085-5d03d8f71200" />

**Comment by AchalaBelokar** [comment]
- [x] Login to maha@jsscp and it is working fine.
- [ ]

**Comment by petmongrels** [comment]
>> maha@rwbnitiuat
this is an issue in the org setup. the org db user has access to another schema which it shouldn't have. such issues to be handled via ticket.

>> cini is not an issue
the dashboard collection is on the next page, there are 81 entries that is why it is not visible on first page
couldn't find cini uat, perhaps the same issue

not able to reproduce date or location filter issue

**Comment by AchalaBelokar** [comment]
- [x] tried with  (maha@iphscd) the report and metabase set is working fine.
- [x] tried with maha@jscsuat_new the report and metabase is working fine
- [x]  tried with maha@power the reports are working fine.
- [ ]

**Comment by petmongrels** [comment]
> * [ ]  Login with maha@goonj and try to setup metabase report  but it is giving me erro
>   java.lang.RuntimeException: Table with name due_visits_view and schema: goonj not found.
>   at org.avni.server.dao.metabase.MetabaseDatabaseRepository.lambda$findTableDetailsByName$1(MetabaseDatabaseRepository.java:124)
>   at java.base/java.util.Optional.orElseThrow(Optional.java:403)
>   at org.avni.server.dao.metabase.MetabaseDatabaseRepository.findTableDetailsByName(MetabaseDatabaseRepository.java:124)
>   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>   at java.base/java.lang.reflect.Method.invoke(Method.java:580)
>   at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
>   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
>   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
>   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
>   at org.avni.server.dao.metabase.MetabaseDatabaseRepository$$SpringCGLIB$$0.findTableDetailsByName()
>   at org.avni.server.service.metabase.DatabaseService.createQuestionForTable(DatabaseService.java:100)
>   at org.avni.server.service.metabase.DatabaseService.createQuestionsForViews(DatabaseService.java:144)
>   at org.avni.server.service.metabase.DatabaseService.addCollectionItems(DatabaseService.java:270)
>   at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.setup(CannedAnalyticsSetupTasklet.java:71)
>   at org.avni.server.importer.batch.metabase.CannedAnalyticsSetupTasklet.execute(CannedAnalyticsSetupTasklet.java:84)
>   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>   at java.base/java.lang.reflect.Method.invoke(Method.java:580)
>   at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
>   at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
>   at

this is happening because the ETL is not working for Goonj due to some ETL issue, unrelated to this.
